
OLED_ENABLE = yes
SPLIT_KEYBOARD = yes
NKRO_ENABLE = yes
LEADER_ENABLE = yes 		# Enable leader keys
LTO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = no
MOUSEKEY_ENABLE = no
WPM_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = no
KEY_OVERRIDE_ENABLE = no
VERBOSE = no
COMMAND_ENABLE = no
STENO_ENABLE = no
BOOTMAGIC_ENABLE = no
TERMINAL_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_LOCK_ENABLE = no
AUDIO_ENABLE = no
VELOCIKEY_ENABLE = no

EXTRAFLAGS+=-flto