
EXTRAKEY_ENABLE = yes
OLED_ENABLE = yes
SPLIT_KEYBOARD = yes
WPM_ENABLE = yes

CONSOLE_ENABLE = no
ENCODER_ENABLE = no
KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE = no
VERBOSE = no
COMMAND_ENABLE = no
STENO_ENABLE = no
BOOTMAGIC_ENABLE = no
TERMINAL_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_LOCK_ENABLE = no
AUDIO_ENABLE = no
VELOCIKEY_ENABLE = no

EXTRAFLAGS+=-flto