
EXTRAKEY_ENABLE = yes
OLED_ENABLE = yes
SPLIT_KEYBOARD = yes
SPLIT_OLED_ENABLE = yes
# TAP_DANCE_ENABLE = yes


OLED_DRIVER = SSD1306

CONSOLE_ENABLE = no
ENCODER_ENABLE = no
KEY_OVERRIDE_ENABLE = no
